name: SharePoint

on:
  workflow_dispatch:

jobs:
  test:
    permissions:
      contents: read
      pages: write
      id-token: write

    runs-on: ubuntu-latest
    name: Share point <-> Git

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install packages
        run: npm install

      - name: Execute tests
        run: npm run test

      - name: Install Allure CommandLine
        if: always()
        run: npm i -g allure-commandline

      - name: Combine Allure
        if: always()
        run: npm run allureCombine

      - name: Upload Test Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Allure report
          path: test/.artifacts/allure-report/complete.html

      - name: Upload Allure Report to SharePoint
        if: always()
        uses: su-dont/share-point-uploader@v2.1
        with:
          sp_url: https://testingmavens-my.sharepoint.com/my?id=%2Fpersonal%2Fanil%5Falexander%5Ftestingmavens%5Fcom%2FDocuments%2FSHAREPOINT
          sp_username: ${{ secrets.username }}
          sp_password: ${{ secrets.password }}
          sp_folder: My files/SHAREPOINT
          sp_file_name: complete.html
          file: test/.artifacts/allure-report/complete.html
